DATABASE_ADDRESS = './database/database.db'
LOGO_REPORT = './images/soon/guiafertil-02.png'
INTERPRETATION_REPORT = '.\\pdf\\Interpretação.pdf'


VERY_HIGH_AVAILABILITY = 'MUITO ALTO'
HIGH_AVAILABILITY = 'ALTO'
AVERAGE_AVAILABILITY = 'MÉDIO'
LOW_AVAILABILITY = 'BAIXO'
VERY_LOW_AVAILABILITY = 'MUITO BAIXO'

GOOD = 'BOM'
VERY_GOOD = 'MUITO BOM'

PH_H2O = 'pH-H2O'
PH_CACL2 = 'pH-CaCl2'
AL = 'Al3+'
SB = 'SB'
H_AL = 'H+Al'
CTC_EFFECTIVE = 't'
CTC_PH7 = 'T'
M = 'm'
V = 'V'

CLAY = 'ARGILA'
P_REM = 'P-REM'
BASE_SATURATION = 'SATURAÇÃO POR BASES'

NC_PLASTER_CLAY = 'NC - ARGILA'
NC_PLASTER_P_REM = 'NC - P-REM'
NC_PLASTER_BS = 'NC - SATURAÇÃO POR BASES'

SOY = 'Soja'
CORN = 'Milho'
SORGHUM = 'Sorgo'
WHEAT = 'Trigo'
BEAN = 'Feijão'

RAINFED = 'SEQUEIRO'
IRRIGATED = 'IRRIGADO'

DIRECT_PLANTING = 'PLANTIO DIRETO'
CONVENTIONAL_PLANTING = 'CONVENCIONAL'

GRADUAL_FERTILIZATION = 'Adubação Gradual'
TOTAL_FERTILIZATION = 'Adubação Total'

CONFIRMED = 'SIM'
NOT_CONFIRMED = 'NÃO'